from elasticsearch:1.7.3

run plugin install elasticsearch/elasticsearch-analysis-kuromoji/2.7.0
run plugin install mobz/elasticsearch-head
run plugin install polyfractal/elasticsearch-inquisitor

cmd elasticsearch

